### ISSUE TITLE
Unable to use tool - "invalid ammibo dump"

### ISSUE THREAD

**Issue by I-Sketchii-I** [jozz024/smash-amiibo-editor#11]
Hello
I am trying to edit my dumped ganondorf amiibo .bin but the application keeps telling me my ganondorf.bin file is an "invalid amiibo dump"
I have tried using "key_retail.bin" as well as "locked-secret.bin + unfixed-info.bin" by putting them in the resources folder. I tried both separately then together but always got the same error.
I dug around and found that there are encrypted and decrypted versions of amiibo .bin files, so I thought maybe mine was decrypted from the dump and needed to be re-encrypted to use with [amiitool](https://github.com/socram8888/amiitool), so I used amiitool to rencrypt it but that didn't work, I also tried decrypting it just to be sure and that didn't work either.
Any help in understanding what's going on would be helpful, as I'm 99% sure my Ganondorf dump is legitimate
Im looking to make some editted amiibo I can add to my flipper zero

Here's a picture of the file in my hex editor if that helps:
![tempsnip](https://user-images.githubusercontent.com/32003492/202848888-07a2be4b-a6cd-46e7-b7ec-e5481a6b504c.png)
I'm assuming my .bin is not getting through the verification of this program or of pyamiibo

**Comment by I-Sketchii-I** [comment]
Sorry for opening an issue, I believe I resolved my issue through the Exion discord server
https://discordapp.com/channels/323988224756154369/323988224756154369/1043503539571400774

**Comment by MiDe-S** [comment]
Archiving solution from the discord 
> did you register the ganon amiibo with the switch itself so it has an owner and a nickname? because that usually fixes it
