### ISSUE TITLE
When trying to build I get an error!

### ISSUE THREAD

**Issue by Astolfo-USBPico** [jozz024/smash-amiibo-editor#8]
pyinstaller main.spec -i SAE.ico

80 INFO: PyInstaller: 5.2
80 INFO: Python: 3.10.5
112 INFO: Platform: Windows-10-10.0.19044-SP0
option(s) not allowed:
  --icon
makespec options not valid when a .spec file is given

**Comment by jozz024** [comment]
mh super sorry, just remove the `-i icon.ico`
